
from tools.script.file_finder import read_file,get_file_info,find_file,list_files,get_markdown_contents,safe_delete_folder,create_folder_structure#这是函数
from tools.script.file_finder import read_file_tool,file_info_tool,file_search_tool,dir_listing_tool,dir_create_tool,delete_folder_tool,create_folder_structure_tool#这是函数结构化的工具
from tools.script.coder_tools import replace_text_between_lines,write_file
from tools.script.coder_tools import file_write_tool,replace_tool
from tools.script.special_tools import Project_Analyst_md_write,Project_Analyst_md_read,Project_Analyst_md_replace,Project_Manager_md_write,Project_Manager_md_read,Project_Manager_md_replace,System_Architect_md_write,System_Architect_md_read,System_Architect_md_replace,Database_Design_md_write,Database_Design_md_read,Database_Design_md_replace
from tools.script.user_tools import user_question_tool
project_tools=[dir_listing_tool]


Project_Analyst_tools=[Project_Analyst_md_write,Project_Analyst_md_read,Project_Analyst_md_replace]
System_Architect_tools=[System_Architect_md_write,System_Architect_md_read,System_Architect_md_replace]
Project_Manager_tools=[Project_Manager_md_write,Project_Manager_md_read,Project_Manager_md_replace]
Database_Design_tools=[Database_Design_md_write,Database_Design_md_read,Database_Design_md_replace]
Task_Extraction_tools=[dir_listing_tool,Project_Analyst_md_read,System_Architect_md_read,Project_Manager_md_read,Database_Design_md_read]
coder_tools=[read_file_tool,file_info_tool,file_search_tool,dir_listing_tool,file_write_tool,replace_tool,dir_create_tool,Project_Analyst_md_read,System_Architect_md_read,Project_Manager_md_read,Database_Design_md_read]#dir_create_tool
dir_create_tools=[System_Architect_md_read,dir_listing_tool,dir_create_tool,delete_folder_tool,create_folder_structure_tool]
code_review_tools=[Project_Analyst_md_read,System_Architect_md_read,Project_Manager_md_read,Database_Design_md_read,dir_listing_tool,read_file_tool]
user_tools=[user_question_tool]
Intelligent_tools=[read_file_tool,file_info_tool,file_search_tool,dir_listing_tool,file_write_tool,replace_tool,dir_create_tool]